services: docker

language:
- node_js
- python

node_js: lts/*
python: 2.7

cache:
  directories:
  - node_modules
  - ~/.local

install:
- docker run --name couchdb1 -d -p 5984:5984 -v "$(pwd)"/conf/couchdb.ini:/opt/couchdb/etc/local.d/docker.ini couchdb
- npm install
- npm start &
# Install CouchApp
- pip install --user couchapp
# Install Argos
- wget https://github.com/Hypertopic/Argos/archive/v4.zip
- unzip v4.zip
- couchapp push Argos-4/app http://localhost:5984/argos
# Set up test fixture
- curl -X PUT localhost:5984/_users
- curl -X PUT localhost:5984/_users/org.couchdb.user:alice -H 'Accept:application/json' -H 'Content-Type:application/json' -d '{"name":"alice", "password":"whiterabbit", "roles":[], "type":"user"}'
- curl -X PUT localhost:5984/_users/org.couchdb.user:riemann -H 'Accept:application/json' -H 'Content-Type:application/json' -d '{"name":"riemann", "password":"secret", "roles":[], "type":"user"}'
script:
- npm test
