port: 1337
service: localhost:5984
#authenticationService: localhost:5985
path: /argos/_design/argos/_rewrite
secret: TO_BE_CHANGED
logFormat: :date[iso] :remote-addr :remote-user :method :url :status :response-time[0]ms :total-time[0]ms ":user-agent"
limit: 500mb
session:
  proxy: true
  cookie:
    sameSite: none
    secure: auto
  secret: TO_BE_CHANGED2
  resave: false
  saveUninitialized: false
  unset: destroy
cors:
  credentials: true
  origin: http://localhost:3000
ldap:
  url: ldap://ldap.forumsys.com
  searchBase: dc=example,dc=com
  searchFilter: (uId={{username}})
record: record

